// Cities of Wyoming JSON
// If you see anything wrong please let me know
// I'm new to JavaScript so please be nice
// This JSON contains every city in Wyoming according to my atlas
// May update with more info at a later time 
// Source is Rand McNally Motor Carriers' Road Atlas 

{
    "Wyoming"= [

    "Adkins Valley",
    "Afton",
    "Alladin",
    "Albany",
    "Albin",
    "Alcova",
    "Allendale",
    "Almy",
    "Alpine",
    "Alta",
    "Alva",
    "Arapahoe",
    "Arlington",
    "Arminto",
    "Arvada",
    "Atlantic City",
    "Auburn",
    "Baggs",
    "Bairoil",
    "Banner",
    "Bar Nunn",
    "Barger",
    "Barnum",
    "Basin",
    "Bear River",
    "Bedford",
    "Beulah",
    "Big Horn",
    "Big Piney",
    "Bill",
    "Bondurant",
    "Bonneville",
    "Bosler",
    "Boulder",
    "Brookhurst",
    "Buffalo",
    "Buford",
    "Burlington",
    "Burns",
    "Burris",
    "Byron",
    "Calpet",
    "Canyon",
    "Carlisle",
    "Carpenter",
    "Carter",
    "Casper",
    "Centennial",
    "Cheyenne",
    "Chugwater",
    "Clearmont",
    "Cody",
    "Cokeville",
    "Colony",
    "Colter Bay",
    "Cora",
    "Cowley",
    "Crowheart",
    "Daniel",
    "Dayton",
    "Deaver",
    "Devils Tower",
    "Diamondville",
    "Dixon",
    "Douglas",
    "Dubois",
    "Duroc",
    "Dwyer",
    "East Thermopolis",
    "Eden",
    "Edgerton",
    "Egbert",
    "Elk Mountain",
    "Emblem",
    "Encampment",
    "Esterbrook",
    "Ethete",
    "Etna",
    "Evanston",
    "Evansville",
    "Fairview",
    "Farson",
    "Farthing",
    "Fontenelle",
    "Fort Bridger",
    "Fort Laramie",
    "Fort Steele",
    "Fort Washakie",
    "Four Corners",
    "Foxpark",
    "Frannie",
    "Freedom",
    "Frontier",
    "Garland",
    "Garrett",
    "Gillette",
    "Glendo",
    "Glenrock",
    "Granger",
    "Grant Village",
    "Grass Creek",
    "Green River",
    "Greybull",
    "Grover",
    "Guernsey",
    "Halfway",
    "Hanna",
    "Harriman",
    "Hartville",
    "Hawk Springs",
    "Hiland",
    "Hillsdale",
    "Hoback",
    "Hoback Junction",
    "Horse Creek",
    "Hudson",
    "Hulett",
    "Huntley",
    "Hyattville",
    "Jackson",
    "Jamestown",
    "Jay Em",
    "Jeffrey City",
    "Jelm",
    "Jenny Lake",
    "Kaycee",
    "Keeline",
    "Kelley",
    "Kemmerer",
    "Kinnear",
    "Kirby",
    "La Barge",
    "La Grange",
    "Lake",
    "Lance Creek",
    "Lander",
    "Laramie",
    "Leiter",
    "Linch",
    "Lingle",
    "Little America",
    "Lonetree",
    "Lost Cabin",
    "Lost Springs",
    "Lovell",
    "Lucerne",
    "Lusk",
    "Lyman",
    "Lysite",
    "Manderson",
    "Manville",
    "Marbleton",
    "McFadden",
    "McKinley",
    "McKinnon",
    "Medicine Bow",
    "Meeteetse",
    "Meridan",
    "Midwest",
    "Midwest Heights",
    "Mills",
    "Moneta",
    "Moorcroft",
    "Moose",
    "Moran",
    "Morton",
    "Mountain Home",
    "Mountain View", //Located South East Wyoming between Green River and Evanston
    "Mountain View", //Suburb of Casper  <^2 different places
    "Muddy Gap",
    "Natrona",
    "New Haven",
    "Newcastle",
    "Node",
    "Old Faithful",
    "Opal",
    "Orchard Valley",
    "Orin",
    "Orpha",
    "Osage",
    "Oshoto",
    "Osmond",
    "Otto",
    "Pahaska",
    "Paradise Valley",
    "Parkman",
    "Pavillion",
    "Pine Bluffs",
    "Pine Haven",
    "Pinedale",
    "Pitchfork Ranch",
    "Point of Rocks",
    "Powder River",
    "Powell",
    "Porspector Village",
    "Quealy",
    "Ralston",
    "Ranchester",
    "Rawlins",
    "Recluse",
    "Red Desert",
    "Reliance",
    "Riverside",
    "Riverton",
    "Robertson",
    "Rock River",
    "Rock Springs",
    "Rockypoint",
    "Rolling Hills",
    "Rozet",
    "Ryan Park",
    "Saddlestring",
    "Sand Draw",
    "Saratoga",
    "Savery",
    "Seminoe Dam",
    "Shawnee",
    "Shell",
    "Sheridan",
    "Shirley Basin",
    "Shoshoni",
    "Sinclair",
    "Skull Creek",
    "Slater",
    "Smoot",
    "South Laramie",
    "South Pass City",
    "South Torrington",
    "Spotted Horse",
    "Story",
    "Sundance",
    "Sunrise",
    "Superior",
    "Sussex",
    "Sweetwater Station",
    "Table Rock",
    "Ten Sleep",
    "Teton Village",
    "Thayne",
    "Thermopolis",
    "Thunder Basin",
    "Tie Siding",
    "Torrington",
    "Tower Junction",
    "Ucross",
    "Upton",
    "Urie",
    "Valley",
    "Van Tassell",
    "Veteran",
    "Vista West",
    "Walcott",
    "Waltman",
    "Wamsutter",
    "Wapiti",
    "West Thumb",
    "Weston",
    "Wheatland",
    "Willwood",
    "Wilson",
    "Winchester",
    "Woods",
    "Worland",
    "Wright",
    "Wyarno",
    "Wyodak",
    "Yoder"
    ]
}